version: 2
jobs:
  build:
    docker:
      - image: 'circleci/python:3.6.2-stretch-browsers'
    working_directory: ~/repo
    steps:
      - checkout      
      - run: python3 test_phone_entry.py 
      - run: python3 test_phone_book.py